server.port=${PORT:8080}

logging.level.org.atmosphere=warn
vaadin.allowed-packages=com.vaadin,org.vaadin,com.flowingcode,io.droidbot.emolga

spring.datasource.url=${SB_DB_URL}
spring.datasource.username=${SB_DB_USER}
spring.datasource.password=${SB_DB_PASS}
spring.jpa.hibernate.ddl-auto=update

emolga.jwt.secret=${EMOLGA_JWT_SECRET}
emolga.jwt.expiration-ms=${EMOLGA_JWT_EXPIRATION_MS}


emolga.supabase.s3.endpoint=${SB_S3_ENDPOINT}
emolga.supabase.s3.region=${SB_S3_REGION}
emolga.supabase.access.key=${SB_S3_ACCESS_KEY}
emolga.supabase.secret.access.key=${SB_S3_SECRET_ACCESS_KEY}
emolga.supabase.bucket.name=sting-ray